/** Static illustrative rows for the Train /models page — not vendor benchmarks. */

export type LlmDeskRow = {
	model: string;
	provider: string;
	category: 'chat' | 'vision' | 'image' | 'audio' | 'video' | 'transcribe' | 'embeddings' | 'rerank' | 'moderation';
	params: string;
	context: string;
	inputPerM: number;
	outputPerM: number;
	mmluPro: number;
	intelligenceIdx: number;
	speedTps: number;
	modelSize: string;
	lastUpdated: string;
	modalities: string[];
	jsonMode: boolean;
	functionCalling: boolean;
	routingFit: number;
	agentFit: number;
};

export type ModelUseCaseCard = {
	rank: number;
	model: string;
	provider: string;
	providerBadge: string;
	description: string;
	speed: number;
	intelligence: number;
	pricePerM: number;
	inputs: string[];
	jsonMode: boolean;
	functionCalling: boolean;
	versions: string[];
	modelSize: string;
	lastUpdated: string;
	benchmarks: { rank: string; name: string; category: string; value: string }[];
	href: string;
};

export const modelUseCaseCards: ModelUseCaseCard[] = [
	{
		rank: 1,
		model: 'LiquidAI LFM2 Transcript',
		provider: 'Liquid AI',
		providerBadge: 'Local',
		description:
			'Private on-device transcript summarization for captions, meetings, live notes, and iterative desk briefs.',
		speed: 4,
		intelligence: 3,
		pricePerM: 0,
		inputs: ['Text'],
		jsonMode: false,
		functionCalling: false,
		versions: ['LFM2-2.6B-Transcript Q4_K_M · 1.6GB · May 2026', 'LFM2-2.6B-Transcript Q8_0 · 2.7GB · May 2026', 'LFM2-2.6B-Transcript F16 · 5.1GB · May 2026'],
		modelSize: '2.6B / 1.6GB Q4_K_M',
		lastUpdated: 'May 2026',
		benchmarks: [
			{ rank: '#1', name: 'Local privacy', category: 'On-device', value: 'yes' },
			{ rank: '#2', name: 'Transcript summaries', category: 'Captions', value: '2.6B' },
			{ rank: '#3', name: 'Memory target', category: 'GGUF', value: '<3GB' },
		],
		href: '/models/liquid-ai/',
	},
	{
		rank: 2,
		model: 'GPT-OSS 120B',
		provider: 'OpenAI',
		providerBadge: 'OpenAI',
		description: 'Open-source 120B parameter model with MXFP4 quantization for efficient inference.',
		speed: 4,
		intelligence: 4,
		pricePerM: 2,
		inputs: ['Text'],
		jsonMode: true,
		functionCalling: true,
		versions: ['GPT-OSS 120B · 117B · Aug 2025', 'GPT-OSS 20B · 21B · Aug 2025'],
		modelSize: '117B',
		lastUpdated: 'Aug 2025',
		benchmarks: [
			{ rank: '#8', name: 'EQBench', category: 'Creative Writing', value: '1152' },
			{ rank: '#7', name: 'Multilingual MMLU', category: 'Multilingual', value: '79.3' },
			{ rank: '#10', name: 'LMArena', category: 'Chat', value: '1355' },
		],
		href: '#model-tester',
	},
	{
		rank: 3,
		model: 'Llama 4 Maverick',
		provider: 'Meta',
		providerBadge: 'Meta',
		description: "Meta's advanced multimodal model with 128 experts, suited to text and image understanding.",
		speed: 5,
		intelligence: 4,
		pricePerM: 0.27,
		inputs: ['Image', 'Text'],
		jsonMode: false,
		functionCalling: true,
		versions: ['Llama 4 Maverick · MoE 128 experts · Apr 2025', 'Llama 4 Scout · MoE · Apr 2025', 'Llama 3.2 1B local · 1B · Sep 2024'],
		modelSize: 'MoE / 128 experts',
		lastUpdated: 'Apr 2025',
		benchmarks: [
			{ rank: '#8', name: 'MMLU-Pro', category: 'General knowledge', value: '62.9' },
			{ rank: '#5', name: 'LiveBench', category: 'General knowledge', value: '55.2' },
			{ rank: '#4', name: 'WebDevArena', category: 'Coding benchmarks', value: '1015' },
		],
		href: '#model-tester',
	},
];

export const llmDeskRows: LlmDeskRow[] = [
	{
		model: 'Claude Opus 4.6',
		provider: 'Anthropic',
		category: 'chat',
		params: 'N/A',
		context: '200K',
		inputPerM: 15,
		outputPerM: 75,
		mmluPro: 82,
		intelligenceIdx: 57,
		speedTps: 53,
		modelSize: 'private',
		lastUpdated: '2026-02',
		modalities: ['Text', 'Image'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 92,
		agentFit: 96,
	},
	{
		model: 'Gemini 3.1 Pro',
		provider: 'Google',
		category: 'chat',
		params: 'N/A',
		context: '1M',
		inputPerM: 2,
		outputPerM: 12,
		mmluPro: 85,
		intelligenceIdx: 57,
		speedTps: 122,
		modelSize: 'private',
		lastUpdated: '2026-03',
		modalities: ['Text', 'Image', 'Audio', 'Video'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 91,
		agentFit: 93,
	},
	{
		model: 'GPT-5.4 (xhigh)',
		provider: 'OpenAI',
		category: 'chat',
		params: 'N/A',
		context: '1M',
		inputPerM: 2.5,
		outputPerM: 15,
		mmluPro: 88,
		intelligenceIdx: 57,
		speedTps: 87,
		modelSize: 'private',
		lastUpdated: '2026-04',
		modalities: ['Text', 'Image', 'Audio'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 94,
		agentFit: 95,
	},
	{
		model: 'DeepSeek V3.2',
		provider: 'DeepSeek',
		category: 'chat',
		params: '685B',
		context: '130K',
		inputPerM: 0.28,
		outputPerM: 0.42,
		mmluPro: 85,
		intelligenceIdx: 52,
		speedTps: 64,
		modelSize: '685B MoE',
		lastUpdated: '2026-01',
		modalities: ['Text'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 84,
		agentFit: 86,
	},
	{
		model: 'Grok 4.3',
		provider: 'xAI',
		category: 'chat',
		params: 'N/A',
		context: '131K',
		inputPerM: 3,
		outputPerM: 15,
		mmluPro: 84,
		intelligenceIdx: 53,
		speedTps: 190,
		modelSize: 'private',
		lastUpdated: '2026-03',
		modalities: ['Text', 'Image'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 86,
		agentFit: 88,
	},
	{
		model: 'LiquidAI LFM2 Transcript',
		provider: 'Liquid AI / local GGUF',
		category: 'transcribe',
		params: '2.6B',
		context: '8K',
		inputPerM: 0,
		outputPerM: 0,
		mmluPro: 0,
		intelligenceIdx: 31,
		speedTps: 0,
		modelSize: '2.6B / 1.6GB Q4',
		lastUpdated: '2026-05',
		modalities: ['Text', 'Transcript'],
		jsonMode: false,
		functionCalling: false,
		routingFit: 79,
		agentFit: 68,
	},
	{
		model: 'gpt-oss-120B (high)',
		provider: 'OpenAI',
		category: 'chat',
		params: '117B',
		context: '128K',
		inputPerM: 0.15,
		outputPerM: 0.6,
		mmluPro: 90,
		intelligenceIdx: 33,
		speedTps: 228,
		modelSize: '117B / MXFP4',
		lastUpdated: '2025-08',
		modalities: ['Text'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 88,
		agentFit: 83,
	},
	{
		model: 'Llama 4 Maverick',
		provider: 'Meta',
		category: 'vision',
		params: 'MoE',
		context: '1M',
		inputPerM: 0.27,
		outputPerM: 0.85,
		mmluPro: 62.9,
		intelligenceIdx: 49,
		speedTps: 170,
		modelSize: '128 experts',
		lastUpdated: '2025-04',
		modalities: ['Text', 'Image'],
		jsonMode: false,
		functionCalling: true,
		routingFit: 82,
		agentFit: 78,
	},
	{
		model: 'Qwen3.6-Plus',
		provider: 'Alibaba / Qwen',
		category: 'chat',
		params: 'N/A',
		context: '1M',
		inputPerM: 0.5,
		outputPerM: 3,
		mmluPro: 83,
		intelligenceIdx: 51,
		speedTps: 155,
		modelSize: 'private',
		lastUpdated: '2026-02',
		modalities: ['Text', 'Image'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 87,
		agentFit: 85,
	},
	{
		model: 'Kimi K2.6',
		provider: 'Moonshot AI',
		category: 'chat',
		params: 'N/A',
		context: '256K',
		inputPerM: 1.2,
		outputPerM: 4.5,
		mmluPro: 81,
		intelligenceIdx: 50,
		speedTps: 112,
		modelSize: 'private',
		lastUpdated: '2026-01',
		modalities: ['Text'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 84,
		agentFit: 82,
	},
	{
		model: 'GLM-5.1',
		provider: 'Zhipu AI',
		category: 'chat',
		params: 'N/A',
		context: '128K',
		inputPerM: 1.4,
		outputPerM: 4.4,
		mmluPro: 80,
		intelligenceIdx: 49,
		speedTps: 126,
		modelSize: 'private',
		lastUpdated: '2026-02',
		modalities: ['Text', 'Image'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 83,
		agentFit: 81,
	},
	{
		model: 'MiniMax M2.7',
		provider: 'MiniMax',
		category: 'chat',
		params: 'N/A',
		context: '1M',
		inputPerM: 0.3,
		outputPerM: 1.2,
		mmluPro: 76,
		intelligenceIdx: 45,
		speedTps: 210,
		modelSize: 'private',
		lastUpdated: '2026-01',
		modalities: ['Text', 'Audio'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 80,
		agentFit: 77,
	},
	{
		model: 'Mistral Large',
		provider: 'Mistral AI',
		category: 'chat',
		params: 'private',
		context: '128K',
		inputPerM: 2,
		outputPerM: 6,
		mmluPro: 82,
		intelligenceIdx: 50,
		speedTps: 145,
		modelSize: 'private',
		lastUpdated: '2025-11',
		modalities: ['Text'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 85,
		agentFit: 82,
	},
	{
		model: 'Command A',
		provider: 'Cohere',
		category: 'rerank',
		params: 'N/A',
		context: '256K',
		inputPerM: 2.5,
		outputPerM: 10,
		mmluPro: 77,
		intelligenceIdx: 44,
		speedTps: 95,
		modelSize: 'private',
		lastUpdated: '2025-10',
		modalities: ['Text', 'Rerank'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 89,
		agentFit: 80,
	},
	{
		model: 'Nomic Embed Text',
		provider: 'Nomic / local',
		category: 'embeddings',
		params: '137M',
		context: '8K',
		inputPerM: 0,
		outputPerM: 0,
		mmluPro: 0,
		intelligenceIdx: 22,
		speedTps: 900,
		modelSize: '274MB',
		lastUpdated: '2026-05',
		modalities: ['Embeddings'],
		jsonMode: false,
		functionCalling: false,
		routingFit: 95,
		agentFit: 60,
	},
	{
		model: 'GPT Image 1',
		provider: 'OpenAI',
		category: 'image',
		params: 'private',
		context: 'N/A',
		inputPerM: 5,
		outputPerM: 40,
		mmluPro: 0,
		intelligenceIdx: 40,
		speedTps: 0,
		modelSize: 'private',
		lastUpdated: '2025-04',
		modalities: ['Image', 'Text'],
		jsonMode: false,
		functionCalling: false,
		routingFit: 76,
		agentFit: 58,
	},
	{
		model: 'Gemini Video',
		provider: 'Google',
		category: 'video',
		params: 'private',
		context: '1M',
		inputPerM: 0.7,
		outputPerM: 2.1,
		mmluPro: 0,
		intelligenceIdx: 43,
		speedTps: 0,
		modelSize: 'private',
		lastUpdated: '2026-02',
		modalities: ['Video', 'Audio', 'Text'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 78,
		agentFit: 70,
	},
	{
		model: 'Whisper Large v3',
		provider: 'OpenAI',
		category: 'audio',
		params: '1.55B',
		context: 'audio',
		inputPerM: 0.6,
		outputPerM: 0,
		mmluPro: 0,
		intelligenceIdx: 34,
		speedTps: 0,
		modelSize: '1.55B',
		lastUpdated: '2024-09',
		modalities: ['Audio', 'Transcribe'],
		jsonMode: true,
		functionCalling: false,
		routingFit: 90,
		agentFit: 62,
	},
	{
		// Illustrative desk row — Liquid LFM2-Audio-1.5B (VoiceBench, ASR, latency): https://www.liquid.ai/blog/lfm2-audio-an-end-to-end-audio-foundation-model
		model: 'LFM2-Audio-1.5B',
		provider: 'Liquid AI',
		category: 'audio',
		params: '1.5B',
		context: 'audio',
		inputPerM: 0.15,
		outputPerM: 0.35,
		mmluPro: 0,
		intelligenceIdx: 57,
		speedTps: 195,
		modelSize: '1.5B',
		lastUpdated: '2025-10',
		modalities: ['Audio', 'Text'],
		jsonMode: true,
		functionCalling: true,
		routingFit: 91,
		agentFit: 80,
	},
	{
		model: 'Omni Moderation',
		provider: 'OpenAI',
		category: 'moderation',
		params: 'private',
		context: '128K',
		inputPerM: 0,
		outputPerM: 0,
		mmluPro: 0,
		intelligenceIdx: 30,
		speedTps: 450,
		modelSize: 'private',
		lastUpdated: '2025-12',
		modalities: ['Text', 'Image'],
		jsonMode: true,
		functionCalling: false,
		routingFit: 96,
		agentFit: 64,
	},
];

export type BenchmarkMini = { label: string; value: number };

export type BenchmarkBlock = {
	slug: string;
	title: string;
	lede: string;
	minis: BenchmarkMini[];
};

export const benchmarkBlocks: BenchmarkBlock[] = [
	{
		slug: 'routing',
		title: 'Routing workflow',
		lede:
			'Classify each request, then send it to a specialized model lane: fast local summaries, vision, rerank, or deep reasoning. Inspired by Agent Recipes and Anthropic workflow patterns.',
		minis: [
			{ label: 'Intent classify', value: 84 },
			{ label: 'Model handoff', value: 78 },
			{ label: 'Latency saved', value: 72 },
		],
	},
	{
		slug: 'parallelization',
		title: 'Parallelization workflow',
		lede:
			'Split a research prompt across search, transcript, ticker, and model-eval workers, then aggregate the results into one source-backed memo.',
		minis: [
			{ label: 'Search workers', value: 79 },
			{ label: 'Evidence merge', value: 67 },
			{ label: 'Conflict flags', value: 61 },
		],
	},
	{
		slug: 'evaluator',
		title: 'Evaluator-optimizer loop',
		lede:
			'One model drafts the brief, another critiques coverage and decides whether more searches are needed before the memo advances.',
		minis: [
			{ label: 'Critique quality', value: 73 },
			{ label: 'Retry discipline', value: 67 },
			{ label: 'Checkpoint diff', value: 81 },
		],
	},
];
